### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/jq#1]
This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
  - [x] Ensure status of concept exercises is "active" or "beta". 
  - [x] Review flow of concepts on Syllabus.
  - [x] Populate "practices" and "prerequisites" for practice exercises.
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [x] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [x] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [ ] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [x] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [x] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by ErikSchierboom** [comment]
A jq track! Neat. 🥳

**Comment by glennj** [comment]
"Add initial exercises" -- almost done. At 25 practice exercises now, 1 concept exercise done and a couple in the pipeline.

**Comment by glennj** [comment]
track icon requested: exercism/website-icons#129

**Comment by glennj** [comment]
Implement tooling: exercism/jq-test-runner#4 gets the test runner live.

**Comment by glennj** [comment]
Implement tooling: exercism/snippet-extractor#59

**Comment by glennj** [comment]
The 12th concept is written. I've checked off the [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises) task.

**Comment by glennj** [comment]
Find Maintainers: Isaac has helpfully self-selected

**Comment by glennj** [comment]
Final task before launch: issue #135

**Comment by glennj** [comment]
No reason to keep this issue hanging around
